### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by maavelar** [tejashah88/Alexa-Utterance-Generator#1]
Hi. I've been trying to access the website but I'm getting this error: 

`This site can’t be reached
alexa-utter-gen.paperplane.io’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by tejashah88** [comment]
Works fine for me, although I did notice this problem not too long ago.

![image](https://user-images.githubusercontent.com/11187343/40929112-a199d650-67d8-11e8-8fe7-1bc6ed24eb82.png)

**Comment by tejashah88** [comment]
Spoke a bit too soon, it seems to be down at random times and then suddenly up again. I've email paperplane.io about this issue.

**Comment by tejashah88** [comment]
@maavelar I've switched the hosting to GitHub pages since paperplane was still being unreliable for their uptime and I haven't received a response from them.
